/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    LoginCitizenWithEmailAndPwdForm: typeof import('./src/components/auth/citizen/LoginCitizenWithEmailAndPwdForm.vue')['default']
    LoginCitizenWithGoogleButton: typeof import('./src/components/auth/citizen/LoginCitizenWithGoogleButton.vue')['default']
    LoginTownCouncilWithPwdForm: typeof import('./src/components/auth/citizen/LoginTownCouncilWithPwdForm.vue')['default']
    PublishSurveyButton: typeof import('./src/components/surveys/buttons/PublishSurveyButton.vue')['default']
    RegisterCitizenWithGoogleButton: typeof import('./src/components/auth/citizen/RegisterCitizenWithGoogleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurveyCitizenView: typeof import('./src/components/surveys/visualiseSurvey/SurveyCitizenView.vue')['default']
    SurveyClientView: typeof import('./src/components/surveys/visualiseSurvey/SurveyClientView.vue')['default']
    SurveyCreateForm: typeof import('./src/components/surveys/forms/SurveyCreateForm.vue')['default']
    SurveyQuestionForm: typeof import('./src/components/surveys/forms/SurveyQuestionForm.vue')['default']
    SurveysList: typeof import('./src/components/surveys/display/SurveysList.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
