/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CitizenQuizzesList: typeof import('./src/components/quizzes/display/CitizenQuizzesList.vue')['default']
    CitizenSurveyListRow: typeof import('./src/components/surveys/display/CitizenSurveyListRow.vue')['default']
    CitizenSurveysList: typeof import('./src/components/surveys/display/CitizenSurveysList.vue')['default']
    CloseSurveyButton: typeof import('./src/components/surveys/buttons/CloseSurveyButton.vue')['default']
    CompileSurveyButton: typeof import('./src/components/surveys/buttons/CompileSurveyButton.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginCitizenWithGoogleButton: typeof import('./src/components/auth/citizen/LoginCitizenWithGoogleButton.vue')['default']
    LoginTownCouncilWithPwdForm: typeof import('./src/components/auth/citizen/LoginTownCouncilWithPwdForm.vue')['default']
    LoginUserWithEmailAndPwdForm: typeof import('./src/components/auth/LoginUserWithEmailAndPwdForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    PublishSurveyButton: typeof import('./src/components/surveys/buttons/PublishSurveyButton.vue')['default']
    QuizCreateForm: typeof import('./src/components/quizzes/QuizCreateForm.vue')['default']
    RegisterCitizenWithGoogleButton: typeof import('./src/components/auth/citizen/RegisterCitizenWithGoogleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurveyCitizenView: typeof import('./src/components/surveys/visualiseSurvey/SurveyCitizenView.vue')['default']
    SurveyCreateForm: typeof import('./src/components/surveys/forms/SurveyCreateForm.vue')['default']
    SurveyQuestionForm: typeof import('./src/components/surveys/forms/SurveyQuestionForm.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TownCouncilSurveysList: typeof import('./src/components/surveys/display/TownCouncilSurveysList.vue')['default']
  }
}
